# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
author: bitnot
title: Flipping bits
email: bitnot01@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Simply playing with GitHub Pages and Jekyll with no goal in mind.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: bitnot01
github_username:  bitnot
# this one is for jekyll-seo-tag
logo: /assets/images/favicon/android-chrome-512x512.png
twitter:
  username: bitnot01
  card: summary

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-gist
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-relative-links

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# To use Utterance comments,  you can going to https://utteranc.es/ get more parameters interpretation.
utterance:
  # Note: Make sure the repo is public, otherwise your readers will not be able to view the issues/comments.
  # Make sure the [utterances app](https://github.com/apps/utterances) is installed on the repo, otherwise users will not be able to post comments.
  #  If your repo is a fork, navigate to it's settings tab and confirm the issues feature is turned on.
  repo: bitnot/bitnot.github.io # Choose the repository utterances will connect to. eg: owner/repo
  issue-term: pathname   # Choose the mapping between blog posts and GitHub issues. 
  theme: github-light # Choose an Utterances theme that matches your blog. 'github-light' is default
  ## Optional
  label:  blog-comments # Choose the label that will be assigned to issues created by Utterances.